"""cross-functional projects: slug, project_agents, member_agents, task fields, task_documents

Revision ID: 24461fee0c65
Revises: 85977934ca52
Create Date: 2026-06-13 02:14:03.638201
"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24461fee0c65'
down_revision: Union[str, None] = '85977934ca52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'agent_id')
    )
    op.create_index(op.f('ix_project_agents_project_id'), 'project_agents', ['project_id'], unique=False)
    op.create_table('project_member_agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('can_talk', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'agent_id')
    )
    op.create_index(op.f('ix_project_member_agents_project_id'), 'project_member_agents', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_member_agents_user_id'), 'project_member_agents', ['user_id'], unique=False)
    op.create_table('task_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('doc_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_documents_task_id'), 'task_documents', ['task_id'], unique=False)
    # tasks: new optional columns
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])

    # projects.slug: add nullable, backfill from name, then enforce NOT NULL + unique
    op.add_column('projects', sa.Column('slug', sa.String(length=220), nullable=True))
    conn = op.get_bind()
    seen: set[str] = set()
    for pid, name in conn.execute(
        sa.text("SELECT id, name FROM projects ORDER BY created_at")
    ).fetchall():
        base = re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-") or "project"
        slug, i = base, 1
        while slug in seen:
            slug, i = f"{base}-{i}", i + 1
        seen.add(slug)
        conn.execute(
            sa.text("UPDATE projects SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": pid},
        )
    op.alter_column("projects", "slug", nullable=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)

    # Backfill: engineering is the agent on every existing project, and every
    # member gets full perms for engineering (one user, one agent today).
    conn.execute(sa.text(
        "INSERT INTO project_agents (id, project_id, agent_id, role, added_by) "
        "SELECT gen_random_uuid(), id, 'engineering', 'primary', created_by FROM projects"
    ))
    conn.execute(sa.text(
        "INSERT INTO project_member_agents "
        "(id, project_id, user_id, agent_id, can_talk, can_approve) "
        "SELECT gen_random_uuid(), project_id, user_id, 'engineering', true, true "
        "FROM project_members"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'owner_id')
    op.drop_column('tasks', 'description')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_column('projects', 'slug')
    op.drop_index(op.f('ix_task_documents_task_id'), table_name='task_documents')
    op.drop_table('task_documents')
    op.drop_index(op.f('ix_project_member_agents_user_id'), table_name='project_member_agents')
    op.drop_index(op.f('ix_project_member_agents_project_id'), table_name='project_member_agents')
    op.drop_table('project_member_agents')
    op.drop_index(op.f('ix_project_agents_project_id'), table_name='project_agents')
    op.drop_table('project_agents')
    # ### end Alembic commands ###
