"""add kind to tasks

Revision ID: e3b0bdf29dfa
Revises: 24461fee0c65
Create Date: 2026-06-14 13:19:16.315717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b0bdf29dfa'
down_revision: Union[str, None] = '24461fee0c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('kind', sa.String(length=20), server_default='task', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'kind')
    # ### end Alembic commands ###
